# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/c-bata/go-prompt"
  version = "0.2.2"

[[constraint]]
  branch = "master"
  name = "yunion.io/x/jsonutils"

[[constraint]]
  #revision = "a14641a90b9e5c72868b7a8358d62ea1d83eab53"
  branch = "master"
  name = "yunion.io/x/sqlchemy"

[[constraint]]
  branch = "master"
  name = "yunion.io/x/log"

[[constraint]]
  branch = "master"
  name = "yunion.io/x/pkg"

[[constraint]]
  branch = "master"
  name = "yunion.io/x/structarg"

[[override]]
    name = "github.com/apache/thrift"
    revision = "e59b73d3c2bf1c328ccb78e683c0462fa1a473c7"
[[override]]
    name = "github.com/ugorji/go"
    revision = "f3cacc17c85ecb7f1b6a9e373ee85d1480919868"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/vmware/govmomi"

[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

[[override]]
  branch = "master"
  name = "github.com/docker/distribution"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "=v1.5.1"

[[override]]
    name = "k8s.io/api"
    branch = "release-1.10"

[[override]]
    name = "k8s.io/apimachinery"
    branch = "release-1.10"

[[override]]
  revision = "0841753fc26e934b715ca7a83dced5bcb721245a"
    name = "k8s.io/apiserver"

[[constraint]]
    name = "k8s.io/client-go"
    branch = "release-7.0"

[[constraint]]
  branch = "release-2.9"
  name = "k8s.io/helm"

[[constraint]]
  revision = "6215fd3290d88563c90827733bfe519f13456a05"
  name = "github.com/banzaicloud/banzai-types"

